INSERT INTO Quiz ([Name], User_ID)
VALUES ('Color quiz', 4)

INSERT INTO Quiz ([Name], User_ID)
VALUES ('Flower quiz', 3)
INSERT INTO Quiz ([Name], User_ID)
VALUES ('Party quiz', 1)
INSERT INTO Quiz ([Name], User_ID)
VALUES ('City quiz', 5)
INSERT INTO Quiz ([Name], User_ID)
VALUES ('Culture quiz', 6)
INSERT INTO Quiz ([Name], User_ID)
VALUES ('Jätterolig quiz', 7)
INSERT INTO Quiz ([Name], User_ID)
VALUES ('Animal quiz', 2)
